'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {parse,inspect,mutate,references}=require('../src/model');
const base=fs.readFileSync('examples/starter.salad.yml','utf8');
const data=s=>parse(s).data;
function set(text,path,key,value,format){return mutate(text,{kind:'set',path,key,value,format});}
test('example has 5 definitions, 5 references and no local errors',()=>{const s=inspect(base);assert.equal(s.definitions.length,5);assert.equal(s.edges.length,5);assert.deepEqual(s.issues,[]);});
test('comments, namespace and JSON-LD annotation survive field edit',()=>{const out=set(base,['$graph',0,'fields',0],'doc','A URL');assert.match(out,/# Schema Salad Studio/);assert.deepEqual(data(out).$namespaces,data(base).$namespaces);assert.deepEqual(data(out).$graph[0].fields[0].jsonldPredicate,data(base).$graph[0].fields[0].jsonldPredicate);});
test('renaming updates scalar, union, map, and nested array references',()=>{const out=set(base,['$graph',0],'name','Resource');const d=data(out);assert.equal(d.$graph[2].fields[2].type.items,'Resource');assert.equal(d.$graph[3].values,'Resource');assert.equal(d.$graph[4].names[1],'Resource');});
test('rename updates shorthand nullable arrays and extends',()=>{const s='- {name: A, type: record}\n- name: B\n  type: record\n  extends: A\n  fields: {a: "A[]?"}\n';const out=set(s,[0],'name','New');assert.equal(data(out)[1].extends,'New');assert.equal(data(out)[1].fields.a,'New[]?');});
test('delete referenced type is blocked',()=>assert.throws(()=>mutate(base,{kind:'delete',path:['$graph',0]}),/reference/));
test('delete field leaves other fields unchanged',()=>{const d=data(mutate(base,{kind:'delete',path:['$graph',2,'fields',0]}));assert.equal(d.$graph[2].fields.length,3);assert.equal(d.$graph[2].fields[0].name,'kind');});
test('add unique fields to a list',()=>{let s=mutate(base,{kind:'addField',path:['$graph',0]});s=mutate(s,{kind:'addField',path:['$graph',0]});assert.deepEqual(data(s).$graph[0].fields.slice(-2).map(f=>f.name),['newField','newField2']);});
test('add fields and edit map shorthand without losing map syntax',()=>{let s='- name: R\n  type: record\n  fields:\n    a: string\n';s=set(s,[0,'fields','a'],'doc','A field');assert.equal(data(s)[0].fields.a.type,'string');s=mutate(s,{kind:'addField',path:[0]});assert.equal(data(s)[0].fields.newField.type,'string');});
test('rename map field changes key, preserving comments',()=>{const s='- name: R\n  type: record\n  fields:\n    # keep me\n    a: string\n';const out=set(s,[0,'fields','a'],'name','b');assert.equal(data(out)[0].fields.b.type,'string');assert.match(out,/# keep me/);});
test('duplicate field rename rejected',()=>assert.throws(()=>set(base,['$graph',0,'fields',0],'name','mediaType'),/already/));
test('duplicate type rename rejected',()=>assert.throws(()=>set(base,['$graph',0],'name','ProductKind'),/already/));
test('structured type can be applied as YAML',()=>{const out=set(base,['$graph',0,'fields',0],'type','["null", {type: array, items: string}]','yaml');assert.deepEqual(data(out).$graph[0].fields[0].type,['null',{type:'array',items:'string'}]);});
test('connection changes exactly the selected type',()=>{const out=mutate(base,{kind:'connect',path:['$graph',2,'fields',0],target:['$graph',0]});assert.equal(data(out).$graph[2].fields[0].type,'Asset');assert.equal(data(out).$graph[2].fields[1].type,'ProductKind');});
test('connection supports map shorthand',()=>{const s='- {name: A, type: record}\n- {name: B, type: record, fields: {a: string}}';assert.equal(data(mutate(s,{kind:'connect',path:[1,'fields','a'],target:[0]}))[1].fields.a,'A');});
test('add definition to single root keeps original',()=>{const s='name: R\ntype: record\nfields: []\n';const out=data(mutate(s,{kind:'addDefinition',path:[],type:'enum'}));assert.equal(out[0].name,'R');assert.equal(out[1].type,'enum');});
for(const kind of ['record','enum','map','union','documentation'])test('create '+kind,()=>{const out=mutate(base,{kind:'addDefinition',path:[],type:kind});assert.equal(data(out).$graph.at(-1).type,kind);assert.equal(inspect(out).issues.filter(x=>x.severity==='error').length,0);});
test('imports and unknown properties survive editing',()=>{let s='custom: 42\n$graph:\n- $import: more.yml\n- name: R\n  type: record\n  custom: yes\n';s=set(s,['$graph',1],'doc','Test');assert.equal(data(s).custom,42);assert.deepEqual(data(s).$graph[0],{$import:'more.yml'});assert.equal(data(s).$graph[1].custom,'yes');});
test('invalid YAML reports an error and refuses mutation',()=>{assert.ok(inspect('[').error);assert.throws(()=>set('[',[],'name','R'));});
test('unquoted null type flagged',()=>assert.ok(inspect('- {name: R, type: record, fields: [{name: x, type: null}]}').issues.some(x=>x.message.includes('Quote'))));
test('valid empty record is allowed',()=>assert.equal(inspect('- {name: R, type: record, documentRoot: true}').issues.length,0));
test('malformed array catches missing items',()=>assert.ok(inspect('- {name: R, type: record, fields: [{name: x, type: {type: array}}]}').issues.some(x=>x.message.includes('items'))));
test('duplicate enum symbols flagged',()=>assert.ok(inspect('- {name: E, type: enum, symbols: [a, a]}').issues.some(x=>x.message.includes('symbols'))));
test('arbitrary metadata is not rewritten by type rename',()=>{const s=base+'\n';const out=set(set(s,['$graph',1],'doc','Asset'),['$graph',0],'name','Resource');assert.equal(data(out).$graph[1].doc,'Asset');});
test('specialization map keys prevent unsafe rename and delete',()=>{const s='- {name: A, type: record}\n- {name: B, type: record, specialize: {A: string}}';assert.throws(()=>set(s,[0],'name','C'),/specialize/);assert.throws(()=>mutate(s,{kind:'delete',path:[0]}),/specialization/);});
test('prototype keys rejected',()=>assert.throws(()=>set(base,['__proto__'],'x','a'),/Invalid/));
test('unknown external URI is not guessed as a local reference',()=>assert.equal(references([{name:'Asset',type:'record'},{name:'R',type:'record',fields:[{name:'x',type:'https://other.org/#Asset'}]}]).length,0));
test('delete sole definition returns a usable empty sequence',()=>assert.deepEqual(data(mutate('name: R\ntype: record\n',{kind:'delete',path:[]})),[]));

test('enum list adds literal strings including YAML keywords',()=>assert.equal(data(mutate(base,{kind:'addSymbol',path:['$graph',1],value:'null'})).$graph[1].symbols.at(-1),'null'));
test('enum list rejects duplicate and empty values',()=>{for(const value of ['radar','  '])assert.throws(()=>mutate(base,{kind:'addSymbol',path:['$graph',1],value}));});
test('enum rename preserves item comment',()=>{const out=mutate('- name: E\n  type: enum\n  symbols:\n    - one # keep\n    - two\n',{kind:'renameSymbol',path:[0],index:0,value:'first'});assert.equal(data(out)[0].symbols[0],'first');assert.match(out,/# keep/);});
test('enum rename duplicate rejected',()=>assert.throws(()=>mutate(base,{kind:'renameSymbol',path:['$graph',1],index:0,value:'radar'}),/already exists/));
test('enum list deletes only specified value',()=>assert.deepEqual(data(mutate(base,{kind:'deleteSymbol',path:['$graph',1],index:1})).$graph[1].symbols,['optical','elevation']));
test('enum stale index and wrong target cannot modify document',()=>{assert.throws(()=>mutate(base,{kind:'deleteSymbol',path:['$graph',1],index:99}),/no longer/);assert.throws(()=>mutate(base,{kind:'addSymbol',path:['$graph',0],value:'x'}),/Select an enum/);});
test('inline named reference automatically creates and removes edges',()=>{const out=set(base,['$graph',0,'fields',1],'type','ProductKind');assert.equal(inspect(out).edges.length,6);assert.equal(inspect(set(out,['$graph',0,'fields',1],'type','string')).edges.length,5);});
test('documentation is not a reference target',()=>assert.equal(references([{name:'Intro',type:'documentation'},{name:'R',type:'record',fields:[{name:'x',type:'Intro'}]}]).length,0));
